regular updates

diff --git a/drivers/ati-graphic-driver/files/ati-graphic-driver.install b/drivers/ati-graphic-driver/files/ati-graphic-driver.install
--- a/drivers/ati-graphic-driver/files/ati-graphic-driver.install
+++ b/drivers/ati-graphic-driver/files/ati-graphic-driver.install
@@ -1,7 +1,7 @@
 . /usr/lib/ybs/funcs
 
 restore() {
-	# restore mesa 
+	# Restore mesa 
 	cd /usr/lib/
 	if [ -f libGL.so.1.2-pkg.mesa ]; then
 		rm libGL.so libGL.so.1 libGL.so.1.2
@@ -10,49 +10,66 @@ restore() {
 		ln -sf libGL.so.1 libGL.so
 	fi
 
-	# restore xorg-server
+	# Restore xorg-server
 	cd /usr/lib/xorg/modules/extensions/
 	if [ -f libglx.so-pkg.xorg-server ]; then
 		rm libglx.so
 		cp libglx.so-pkg.xorg-server libglx.so 
 	fi
 
-	# restore xorg.conf
+	# Restore xorg.conf
 	cd /etc/X11 
 	if ls xorg.conf.original-* >/dev/null 2>/dev/null; then
 		cp $(ls xorg.conf.original-* |sort -ur |head -n1) xorg.conf
 	fi
+
 	return 0
 }
 
-post_install() {
+pre_install() {
+	# Dual graphic cards
 	if lspci |grep VGA |grep "ATI Technologies"; then
 		if lspci |grep VGA |grep "Intel Corporation"; then
 			echo "* Error: ATI and Intel Dual-Video-Cards found!"
 			echo "* You MUSE select discrete grahpic at BIOS and reinstall manually."
 			restore
-			return 0
-		else	
-			ypkg_domk build $1 $2
-			if ! modinfo fglrx >/dev/null; then
-				echo "* Error: build fglrx kernenl module failed!"
-				restore
-				return 0
-			fi
-			aticonfig --initial
-			cat > /etc/modprobe.d/blacklist-fglrx.conf <<EOF
+			return 1
+		fi
+	else
+		# 
+		echo "* Error: ATI graphic card not found!"
+		echo "* You do not need this driver, please remove manually."
+		restore
+		return 1
+	fi
+
+	return 0
+}
+
+post_install() {
+	# Build fglrx.ko
+	ypkg_domk build $1 $2
+
+	# Check fglrx.ko
+	if ! modinfo fglrx >/dev/null; then
+		echo "* Error: build fglrx kernenl module failed!"
+		restore
+		return 1
+	fi
+
+	# Setup xorg.conf
+	aticonfig --initial
+
+	# Setup modprobe blacklist
+	cat > /etc/modprobe.d/blacklist-fglrx.conf <<EOF
 # Advanced Micro Devices, Inc.
 # radeon conflicts with AMD Linux Graphics Driver
 blacklist radeon
 EOF
-			update-initramfs -d -u
-		fi
-	else
-		echo "* Error: ATI graphic card not found!"
-		echo "* You do not need this driver, please remove manually."
-		restore
-		return 0
-	fi
+	# Update initramfs
+	update-initramfs -d -u
+	
+	#
 	gnome2_desktop_database_update
 
 	echo '* By using this package you accept the ATI license,'
@@ -65,25 +82,37 @@ EOF
 }
 
 post_remove() {
-	if lspci |grep VGA |grep "ATI Technologies"; then
-		rm  /etc/modprobe.d/blacklist-fglrx.conf /etc/X11/xorg.conf 
-		ypkg_domk delete $1 $2
-		rm  -rf /usr/src/"$1-$2"
-		update-initramfs -d -u
+	# Delete modprobe balcklist
+	[ -f /etc/modprobe.d/blacklist-fglrx.conf ] && rm /etc/modprobe.d/blacklist-fglrx.conf 
+	
+	# Delete xorg.conf
+	if [ -f /etc/X11/xorg.conf ]; then
+		grep -w Driver /etc/X11/xorg.conf |grep -w fglrx && rm /etc/X11/xorg.conf
 	fi
 
+	# Delete fglrx.ko
+	ypkg_domk delete $1 $2
+
+	# Delete module source
+	rm  -rf /usr/src/"$1-$2"
+	
+	# Update initramfs
+	update-initramfs -d -u
+
+	# Restore libGL and libglx
 	restore
 
+	#
 	echo '* You must logout session for the changes to take effect.'
 
 	return 0
 }
 
 post_upgrade()  {
-	post_install
+	post_install $1 $2
 }
 
 post_downgrade() {
-	post_install
+	post_install $1 $2
 }
 
diff --git a/drivers/nvidia-graphic-driver/files/nvidia-graphic-driver.install b/drivers/nvidia-graphic-driver/files/nvidia-graphic-driver.install
--- a/drivers/nvidia-graphic-driver/files/nvidia-graphic-driver.install
+++ b/drivers/nvidia-graphic-driver/files/nvidia-graphic-driver.install
@@ -25,16 +25,37 @@ restore() {
 	return 0
 }
 
-post_install() {
+pre_install() {
 	if lspci |grep VGA |grep nVidia; then
-		ypkg_domk build $1 $2 "-f Makefile.kbuild module"
-		if ! modinfo nvidia >/dev/null; then
-			echo "* Error: build nvidia kernenl module failed!"
+		if lspci |grep VGA |grep "Intel Corporation"; then
+			echo "* Error: nVidia and Intel Dual-Video-Cards found!"
 			restore
-			return 0
+			return 1
 		fi
-		nvidia-xconfig
-		cat > /etc/modprobe.d/blacklist-nvidia.conf <<EOF
+	else
+		echo "* Error: nvidia graphic card not found!"
+		echo "* You do not need this driver, please remove manually."
+		restore
+		return 1
+	fi
+
+	return 0
+}
+
+post_install() {
+	# Build nvidia.ko
+	ypkg_domk build $1 $2 "-f Makefile.kbuild module"
+
+	# Check nvidia.ko
+	if ! modinfo nvidia >/dev/null; then
+		echo "* Error: build nvidia kernenl module failed!"
+		restore
+		return 1
+	fi
+
+	# Setup xorg.conf
+	nvidia-xconfig
+	cat > /etc/modprobe.d/blacklist-nvidia.conf <<EOF
 blacklist nouveau
 options nouveau modeset=0
 
@@ -44,15 +65,13 @@ blacklist nvidia-173
 
 blacklist nvidia-96
 EOF
-		update-initramfs -d -u
-	else
-		echo "* Error: nvidia graphic card not found!"
-		echo "* You do not need this driver,please remove manually."
-		restore
-		return 0
-	fi
+	# Update initramfs
+	update-initramfs -d -u
+	
+	#	
 	gnome2_desktop_database_update
 
+	# License
 	echo '* By using this package you accept the NVIDIA license,'
 	echo '* which has been installed in /usr/share/licenses/nvidia/LICENSE'
 	echo '* If you do not accept this license, you must remove the package immediately.'
@@ -63,24 +82,37 @@ EOF
 }
 
 post_remove() {
-	if lspci |grep VGA |grep nVidia; then
-		rm  /etc/modprobe.d/blacklist-nvidia.conf /etc/X11/xorg.conf 
-		ypkg_domk delete $1 $2
-		rm  -rf /usr/src/"$1-$2"
-		update-initramfs -d -u
+	# Delete mopdrobe blacklist
+	[ -f /etc/modprobe.d/blacklist-nvidia.conf ] && rm /etc/modprobe.d/blacklist-nvidia.conf
+
+	# Delete xorg.conf
+	if [ -f /etc/X11/xorg.conf ]; then
+		grep -w Driver /etc/X11/xorg.conf |grep -w nvidia && rm /etc/X11/xorg.conf
 	fi
+
+	# Delete nvidia.ko
+	ypkg_domk delete $1 $2
+
+	# Delete module source 
+	rm  -rf /usr/src/"$1-$2"
+
+	# Update initramfs
+	update-initramfs -d -u
 	
+	# restore libGL and libglx.so
 	restore
+
+	# Mesassge
 	echo '* You must logout your session for the changes to take effect.'
 
 	return 0
 }
 
 post_upgrade()  {
-	post_install
+	post_install $1 $2
 }
 
 post_downgrade() {
-	post_install
+	post_install $1 $2
 }
 
