add KDE 4.8.4 (big commit)

diff --git a/gnome-extra/gdm/files/gdm.install b/gnome-extra/gdm/files/gdm.install
--- a/gnome-extra/gdm/files/gdm.install
+++ b/gnome-extra/gdm/files/gdm.install
@@ -1,5 +1,9 @@
 . /usr/lib/ybs/funcs
 
+ldm=lightdm.service
+gdm=gdm.service
+files="$ldm $gdm"
+
 post_install() {
 	# Creat gdm user and groups
 	douseradd -c "gdm user" -d "/var/lib/gdm" -s "/bin/false" -r "gdm"
@@ -29,45 +33,45 @@ post_install() {
 	chown -R gdm:gdm /var/lib/gdm/
 	
 	# Systemd unit
-	systemctl enable gdm.service
+	if systemctl enable $files 2>/dev/null; then
+		echo "* $files are exits, I choose $ldm."
+		systemctl disable $files
+		systemctl enable $ldm
+	fi	
 
 	return 0
 }
 
 post_upgrade() {
-	# Reload
-	gnome2_desktop_database_update
-	gnome2_gtk_immodules_update
-
-	# Setup default gconf value
-	[ -f /etc/gdm/custom.conf ] || cp /etc/gdm/custom.conf.ori /etc/gdm/custom.conf
-
-	# Update hicolor icons
-	gnome2_icon_cache_update
-
-	# Setting permission for /var/lib/gdm
-	chown -R gdm:gdm /var/lib/gdm
-	chown -R gdm:gdm /var/lib/gdm/
-
-	# Systemd unit
 	systemctl --system daemon-reload
-	systemctl enable gdm.service
-
-	return 0
+	post_install
 }
 
 post_downgrade() {
 	post_upgrade
 }
 
-
 pre_remove() {
-	systemctl disable gdm.service
+	systemctl disable gdm.service ||true
 }
 
 post_remove() {
-	[ -f /etc/gdm/custom.conf ] && rm /etc/gdm/custom.conf
-	douserdel -r "gdm"
-	gnome2_desktop_database_update
+	#
+	rm /etc/gdm/custom.conf 2>/dev/null
+
+	#
+	douserdel -r gdm
+	dogroupdel gdm
+
+	#
+	if ! systemctl enable $ldm 2>/dev/null; then
+		echo "* $gdm was removed, but $ldm is not found or broken"
+                echo "* You may launch desktop manually."
+	else
+		echo "* $gdm was removed, but $ldm is found"
+		echo "* use $ldm for display-manager."
+        fi
+ 
+ 	return 0
 }
 
