Gnome update to 3.8.1

diff --git a/app-misc/ca-certificates/files/ca-certificates.install b/app-misc/ca-certificates/files/ca-certificates.install
--- a/app-misc/ca-certificates/files/ca-certificates.install
+++ b/app-misc/ca-certificates/files/ca-certificates.install
@@ -1,25 +1,22 @@
-. /usr/lib/ybs/funcs
 
 post_install() {
-    /usr/sbin/update-ca-certificates --fresh >/dev/null 2>&1
+    /usr/sbin/update-ca-certificates --fresh ||true
 }
 
 pre_remove() {
-    # clean up certificates
+    # Clean up certificates
     local _backup=$(mktemp)
     mv /etc/ca-certificates.conf ${_backup}
     echo >/etc/ca-certificates.conf
-    /usr/sbin/update-ca-certificates --fresh >/dev/null 2>&1
+    /usr/sbin/update-ca-certificates --fresh
     mv ${_backup} /etc/ca-certificates.conf
 }
 
 post_remove() {
-    # remove the cert file if it is empty
-    [[ -s /etc/ssl/certs/ca-certificates.crt ]] || rm -f /etc/ssl/certs/ca-certificates.crt
-    return 0
+    # Remove the cert file if it is empty
+    [[ ! -s /etc/ssl/certs/ca-certificates.crt ]] && rm -f /etc/ssl/certs/ca-certificates.crt ||true
 }
 
 post_upgrade() {
     post_install
 }
-
