rebuild driver category: foo-driver for binary kernel module package foo-source for kernel module source package

diff --git a/drivers/ati-graphic/files/ati-graphic-utils.install b/drivers/ati-graphic/files/ati-graphic-utils.install
--- a/drivers/ati-graphic/files/ati-graphic-utils.install
+++ b/drivers/ati-graphic/files/ati-graphic-utils.install
@@ -47,12 +47,11 @@ pre_install() {
 }
 
 post_install() {
-	# Build fglrx.ko
-	ypkg_domk build $1 $2
-
 	# Check fglrx.ko
-	if ! modinfo fglrx >/dev/null; then
-		echo "* Error: build fglrx kernenl module failed!"
+	if ! modprobe fglrx >/dev/null; then
+		echo "* Error: fglrx kernenl module not found or modprobe failed!"
+		echo "* Please install ati-graphic-driver or ati-graphic-source "
+		echo "* if you are using ATI graphic card."
 		restore
 		return 1
 	fi
@@ -91,9 +90,6 @@ post_remove() {
 		grep -w Driver /etc/X11/xorg.conf |grep -w fglrx && rm /etc/X11/xorg.conf
 	fi
 
-	# Delete fglrx.ko
-	ypkg_domk delete $1 $2
-
 	# Delete module source
 	rm  -rf /usr/src/"$1-$2"
 	
@@ -108,6 +104,14 @@ post_remove() {
 	echo '* You must logout session for the changes to take effect.'
 
 	return 0
+}
+
+pre_upgrade() {
+	pre_install
+}
+
+pre_downgrade() {
+	pre_install
 }
 
 post_upgrade()  {
diff --git a/drivers/nvidia-graphic-96/files/nvidia-graphic-96-utils.install b/drivers/nvidia-graphic-96/files/nvidia-graphic-96-utils.install
--- a/drivers/nvidia-graphic-96/files/nvidia-graphic-96-utils.install
+++ b/drivers/nvidia-graphic-96/files/nvidia-graphic-96-utils.install
@@ -43,14 +43,12 @@ pre_install() {
 }
 
 post_install() {
-	# Build nvidia.ko
-	# disable checking gcc used to compile kernel and current gcc.
-	export IGNORE_CC_MISMATCH="1"
-	ypkg_domk build $1 $2 "-f Makefile.kbuild module"
-
 	# Check nvidia.ko
-	if ! modinfo nvidia >/dev/null; then
-		echo "* Error: build nvidia kernenl module failed!"
+	if ! modprobe nvidia >/dev/null; then
+		echo "* Error: nvidia kernel module not found or modprobe failed!"
+		echo "* Please install nvidia-graphic-96-driver or nvidia-graphic-96-source"
+		echo "* if you are using nvidia graphic card."
+		echo 
 		restore
 		return 1
 	fi
@@ -65,7 +63,6 @@ blacklist lbm-nouveau
 EOF
 	# Update initramfs
         depmod -a
-        depmod -a
 	update-initramfs -d -u
 	
 	#	
@@ -76,7 +73,7 @@ EOF
 	echo '* which has been installed in /usr/share/licenses/nvidia/LICENSE'
 	echo '* If you do not accept this license, you must remove the package immediately.'
 	echo 
-	echo '* You must reboot your computer for the changes to take effect.'
+	echo '* Reboot your computer for the changes to take effect.'
 
 	return 0
 }
@@ -90,14 +87,10 @@ post_remove() {
 		grep -w Driver /etc/X11/xorg.conf |grep -w nvidia && rm /etc/X11/xorg.conf
 	fi
 
-	# Delete nvidia.ko
-	ypkg_domk delete $1 $2
-
 	# Delete module source 
 	rm  -rf /usr/src/"$1-$2"
 
 	# Update initramfs
-        depmod -a
         depmod -a
 	update-initramfs -d -u
 	
@@ -105,9 +98,17 @@ post_remove() {
 	restore
 
 	# Mesassge
-	echo '* You must logout your session for the changes to take effect.'
+	echo '* Re-login session for the changes to take effect.'
 
 	return 0
+}
+
+pre_upgrade() {
+	pre_install
+}
+
+pre_downgrade() {
+	pre_install
 }
 
 post_upgrade()  {
diff --git a/drivers/nvidia-graphic/files/nvidia-graphic-utils.install b/drivers/nvidia-graphic/files/nvidia-graphic-utils.install
--- a/drivers/nvidia-graphic/files/nvidia-graphic-utils.install
+++ b/drivers/nvidia-graphic/files/nvidia-graphic-utils.install
@@ -44,8 +44,8 @@ pre_install() {
 
 post_install() {
 	# Check nvidia.ko
-	if ! modinfo nvidia >/dev/null; then
-		echo "* Error: modprobe nvidia kernel module failed!"
+	if ! modprobe nvidia >/dev/null; then
+		echo "* Error: nvidia kernel module not found or modprobe failed!"
 		echo "* Please install nvidia-graphic-driver or nvidia-graphic-source"
 		echo "* if you are using nvidia graphic card."
 		echo 
@@ -101,6 +101,14 @@ post_remove() {
 	echo '* Re-login session for the changes to take effect.'
 
 	return 0
+}
+
+pre_upgrade() {
+	pre_install
+}
+
+pre_downgrade() {
+	pre_install
 }
 
 post_upgrade()  {
