regular updates

diff --git a/sys-apps/systemd/files/reload b/sys-apps/systemd/files/reload
--- a/sys-apps/systemd/files/reload
+++ b/sys-apps/systemd/files/reload
@@ -2,14 +2,19 @@
 #
 # wrapper of systemctl start
 #
-echo " This is a wrapper of systemctl, e.g:"
-echo " \"reload gdm\" to reload gdm"
-echo
 
-if [ "x$1" != "x" ]; then
-	dm=${1%%.service}
-	systemctl reload "$(basename $dm)".service
-	systemctl status "$(basename $dm)".service
+if [ "x$@" = "x" ]; then
+	echo "* Error, please specify a systemd unit."
+	exit 1
+else
+	echo "* This is a wrapper of systemctl, try to reload $1."
+	echo
+
+	if [ "x$1" != "x" ]; then
+		dm=${1%%.service}
+		systemctl reload "$(basename $dm)".service
+		systemctl status "$(basename $dm)".service
+	fi
 fi
 
 exit 0
diff --git a/sys-apps/systemd/files/start b/sys-apps/systemd/files/start
--- a/sys-apps/systemd/files/start
+++ b/sys-apps/systemd/files/start
@@ -2,14 +2,18 @@
 #
 # wrapper of systemctl start
 #
-echo " This is a wrapper of systemctl, e.g:"
-echo " \"start gdm\" to start gdm"
-echo
+if [ "x$@" = "x" ]; then
+        echo "* Error, please specify a systemd unit."
+        exit 1
+else
+	echo "* This is a wrapper of systemctl, try to start $1."
+	echo
 
-if [ "x$1" != "x" ]; then
-	dm=${1%%.service}
-	systemctl start "$(basename $dm)".service
-	systemctl status "$(basename $dm)".service
+	if [ "x$1" != "x" ]; then
+		dm=${1%%.service}
+		systemctl start "$(basename $dm)".service
+		systemctl status "$(basename $dm)".service
+	fi
 fi
 
 exit 0
diff --git a/sys-apps/systemd/files/status b/sys-apps/systemd/files/status
--- a/sys-apps/systemd/files/status
+++ b/sys-apps/systemd/files/status
@@ -2,13 +2,17 @@
 #
 # wrapper of systemctl start
 #
-echo " This is a wrapper of systemctl, e.g:"
-echo " \"status gdm\" to status gdm"
-echo
+if [ "x$@" = "x" ]; then
+        echo "* Error, please specify a systemd unit."
+        exit 1
+else
+	echo "* This is a wrapper of systemctl, try to status $1."
+	echo
 
-if [ "x$1" != "x" ]; then
-	dm=${1%%.service}
-	systemctl status "$(basename $dm)".service
+	if [ "x$1" != "x" ]; then
+		dm=${1%%.service}
+		systemctl status "$(basename $dm)".service
+	fi
 fi
 
 exit 0
